spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:demo
spring.h2.console.enabled=true
#H2+JPA \uC0AC\uC6A9\uC2DC data.sql\uC744 \uC0AC\uC6A9\uD558\uC5EC \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uCD08\uAE30 \uB370\uC774\uD130 \uC124\uC815\uC774 \uD544\uC694\uD558\uB2E4\uBA74 \uB2E4\uC74C\uACFC \uAC19\uC774 JPA\uAC00 \uBA3C\uC800 \uD14C\uC774\uBE14 \uC0DD\uC131\uD55C \uD6C4\uC5D0 \uCD08\uAE30\uD654\uB97C \uD558\uB3C4\uB85D \uC124\uC815\uC774 \uD544\uC694
spring.jpa.defer-datasource-initialization=true
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
