package com.example.demo;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.content.Media;
import org.springframework.ai.openai.OpenAiChatModel;
import org.springframework.ai.openai.OpenAiChatOptions;
import org.springframework.ai.openai.api.OpenAiApi;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.util.MimeTypeUtils;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

@SpringBootTest
public class AudioMultiModalTests {
    private static final Logger log = LoggerFactory.getLogger(AudioMultiModalTests.class);

    @Autowired
    private OpenAiChatModel chatModel;

    @Test
    public void testMultiModalWithAudioInput() {
        // 오디오 미디어 준비
        Resource resource = new ClassPathResource("/audio/sample_audio.mp3");
        Media media = Media.builder()
                .mimeType(MimeTypeUtils.parseMimeType("audio/mp3"))
                .data(resource).build();

        // 준비한 미디어와 텍스트로 사용자 메시지 준비
        UserMessage message = UserMessage.builder()
                .text("이 오디오 파일의 내용을 요약해 주세요")
                .media(media).build();

        // 기본 GPT 모델은 오디오를 입력으로 받지 못 하므로 오디오 입력이 가능한 챗모델을 지정
        ChatOptions chatOptions = OpenAiChatOptions.builder()
                //.model(OpenAiApi.ChatModel.GPT_4_O_AUDIO_PREVIEW)
                .model("gpt-audio")
                .build();

        // 챗옵션과 사용자 메시지를 사용하여 프롬프트 구성하고 호출
        ChatResponse response = chatModel.call(new Prompt(message, chatOptions));

        // 생성된 답변과 답변을 생성한 모델 이름 출력
        log.info("{}", response.getResult().getOutput().getText());
        log.info("generated by {}", response.getMetadata().getModel());
    }

    @Test
    public void testMultiModalWithAudioOutput() throws IOException {

        String message = "스프링부트에 대해 간단하게 설명해 주세요";

        ChatOptions chatOptions = OpenAiChatOptions.builder()
                .model(OpenAiApi.ChatModel.GPT_4_O_AUDIO_PREVIEW)
                //.model("gpt-audio")
                .outputModalities(List.of("text", "audio"))
                .outputAudio(new OpenAiApi.ChatCompletionRequest.AudioParameters(
                        OpenAiApi.ChatCompletionRequest.AudioParameters.Voice.NOVA,
                        OpenAiApi.ChatCompletionRequest.AudioParameters.AudioResponseFormat.MP3)
                ).build();

        ChatResponse response = chatModel.call(new Prompt(message, chatOptions));

        String audioTranscript = response.getResult().getOutput().getText();
        log.info("audio transcript {}", audioTranscript);
        log.info("model {}, prompt {}, completion {}",
                response.getMetadata().getModel(),
                response.getMetadata().getUsage().getPromptTokens(),
                response.getMetadata().getUsage().getCompletionTokens()
        );

        byte[] audio = response.getResult().getOutput().getMedia().getFirst().getDataAsByteArray(); // audio data
        Files.write(Paths.get("D:\\archive\\audio\\ai_chat_audio.mp3"), audio);
    }
}
