# DDL \uC0DD\uC131
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/generated/ddl/create.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata

# DDL \uC0DD\uC131\uC6A9 \uD504\uB85C\uD544\uC5D0\uC11C\uB294 \uBA85\uC2DC \uCD94\uCC9C
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

