spring.application.name=demo
#spring.h2.console.enabled=true

# DEBUG: \uD544\uD130 \uC21C\uC11C \uD655\uC778 \uBC0F \uC694\uCCAD\uBCC4 \uC804\uCCB4 \uD544\uD130 \uD750\uB984 \uCD94\uC801
logging.level.org.springframework.security=DEBUG

# Spring Session for Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.username=myuser
#spring.data.redis.password=mypass
#spring.session.data.redis.namespace=myuser:session
#spring.session.data.redis.configure-action=none
#spring.session.timeout=30m
