spring.application.name=demo
#spring.h2.console.enabled=true

# DEBUG: \uD544\uD130 \uC21C\uC11C \uD655\uC778 \uBC0F \uC694\uCCAD\uBCC4 \uC804\uCCB4 \uD544\uD130 \uD750\uB984 \uCD94\uC801
logging.level.org.springframework.security=DEBUG
