spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=1.0

# vector - https://docs.spring.io/spring-ai/reference/api/vectordbs/pgvector.html
spring.datasource.url=jdbc:postgresql://13.125.211.92:5432/tutor
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.datasource.username=tutor
spring.datasource.password=tutorp

spring.jpa.hibernate.ddl-auto=create