spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=1.0

# vector - https://docs.spring.io/spring-ai/reference/api/vectordbs/pgvector.html
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.datasource.username=myuser
spring.datasource.password=mypass

spring.jpa.hibernate.ddl-auto=create